services:
  - type: web
    name: aolrc-inventory-live-test
    runtime: docker
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    preDeployCommand: python -m flask --app run.py db upgrade
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: REMEMBER_COOKIE_SECURE
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
